### ISSUE TITLE
DeribitV2Client and JsonRpcClient to accept ILogger instance

### ISSUE THREAD

**Issue by badokun** [psollberger/DeriSock#10]
Currently both these classes uses the global static logger., defined like below:
```
    protected readonly ILogger Logger = Log.Logger;
```

In my use case I have multiple connections to exchanges (one per clientId/secret pair), and would like to use a ILogger instance that has context defined, e.g.

```
        _logger = logger.ForContext(nameof(ExchangeName), ExchangeName); 
```

where `ExchangeName` is dynamically generated, e.g. `deribit-mainnet-{clientId}`

Two options exist, either take the ILogger as an optional argument, or remove the `readonly` statement from  `protected readonly ILogger Logger = Log.Logger;` so it can be set by a derived class.

My preference would be for the former, what do you think?

**Comment by psollberger** [comment]
I created a PR. Can you take a look and tell me if that fits your needs?

This can change in the future because I already had in mind to make the code compatible with dependency injection and i'm not sure if the current solution will work with that.

**Comment by badokun** [comment]
That's perfect, thanks. Will wait for the merge, which should produce a new Nuget package
