### ISSUE TITLE
Add more target frameworks

### ISSUE THREAD

**Issue by psollberger** [psollberger/DeriSock#13]
The goal is to support the following target frameworks:

- netstandard2.1
- net46
- net48
- net5.0
- net6.0

Maybe it's not possible to support all of them due to type dependencies but i'll try anyway

**Comment by badokun** [comment]
fyi, I'm using DeriSock 0.3.2 in my net6.0 project, no problems.

**Comment by psollberger** [comment]
@badokun i'm not worried about net6.0 but the netstandard ones are a bit problematic
