### ISSUE TITLE
Remove unnecessary duplication of `GetOptionType` and `GetInstrumentType` logic

### ISSUE THREAD

**Issue by psollberger** [psollberger/DeriSock#28]
Unfortunately unnecessary duplication was introduced with this merge request. `GetOptionType` and `GetInstrumentType` is copied in other areas of the project. E.g.
https://github.com/psollberger/DeriSock/blob/11191b9564d474e268c70478554aaa930d696427/DeriSock/Model/TickerNotification.cs#L167 and https://github.com/psollberger/DeriSock/blob/11191b9564d474e268c70478554aaa930d696427/DeriSock/Model/Instrument.cs#L114 and https://github.com/psollberger/DeriSock/blob/11191b9564d474e268c70478554aaa930d696427/DeriSock/Model/OrderBook.cs#L189

May I suggest the introduction of a string extension class so that you can call `xxx.InstrumentName.GetOptionType()` or `xxx.InstrumentName.GetInstrumentType()`. This will ensure there's no duplication

_Originally posted by @badokun in https://github.com/psollberger/DeriSock/issues/27#issuecomment-1129578063_

**Comment by psollberger** [comment]
Closed by commit 8246b810a336041c59cd01a5cf13085ce203fd76

**Comment by badokun** [comment]
Great, thanks!
