### ISSUE TITLE
Add array of channels for subscriptions see example

### ISSUE THREAD

**Issue by Tradyn** [psollberger/DeriSock#35]
Request
`
{
  "method": "public/subscribe",
  "params": {
    "channels": [
      "book.BTC-26AUG22-23000-C.100ms",
      "book.BTC-28OCT22-25000-P.100ms",
      "book.BTC-2SEP22-26000-C.100ms"
    ]
  },
  "jsonrpc": "2.0",
  "id": 1
}
`

Result
`{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    "book.BTC-2SEP22-26000-C.100ms",
    "book.BTC-28OCT22-25000-P.100ms",
    "book.BTC-26AUG22-23000-C.100ms"
  ],
  "usIn": 1660597049881206,
  "usOut": 1660597049881358,
  "usDiff": 152,
  "testnet": true
}`

Maybe object array for params.
I cannot see a clean way to add this, otherwise I would change myself

Also..
I have added soo many features to this project.. but codebase has completely changed, so probably going to have to add all new features by hand...

**Comment by psollberger** [comment]
Hi @Tradyn 

Thank you for creating this issue. That's certainly something the library will benefit from.

**First of all**

I am very sorry for any inconvinience my restructuring is causing (and it's not quite done yet).
To give more insight on what i'm planing, I updated an existing issue with what's on my mind: https://github.com/psollberger/DeriSock/issues/12

**Back to the topic**

Because of the way the subscription system works internally in DeriSock, this is no trivial task.
When subscribing to a channel, a callback MUST be provided. DeriSock executes this callback when a notification for this channel arrives, so it needs to have it.

I can think some kind of a `SubscribeMany` Method that can accept multiple channel/callback pairs.

Is this something that would suite your needs?

**Comment by Tradyn** [comment]
It was not too bad as you had added a lot of the fixes I made, looked bad, but was OK so don't worry.

Ideally we want RX streams rather than these callbacks.

I was going to do an RX or SignalR fork, but I just don't have the time at the moment.

** See the exchange lib I have in my repos **

**Comment by psollberger** [comment]
I don't know RX at all and have little to no knowledge about SignalR.

Can you elaborate a bit more on how that would work?
What problem will that solve that exists with the callbacks or how will it make the subscription notifications easier to use?

**Comment by psollberger** [comment]
@Tradyn, I really need more information of what you have in mind exactly.
Can you give me a direkt link to the part (of the mentioned repo) you refer to and maybe some short explanation of the concept you would like to see?

If not, the best thing I can do is the mentioned `SubscribeMany`, a "catch all"-Interface or alike.

**Comment by psollberger** [comment]
@Tradyn, I tried something. Please take a look in this branch: https://github.com/psollberger/DeriSock/tree/35-add-array-of-channels-for-subscriptio

I added a small example in the DevTools project that showcases what I did. Is this mechanic what you had in mind?

In **Program.cs**

```cs
  public static async Task Main(string[] args)
  {
    try {
      // Create a CancellationTokenSource to be able to cancel (unsubscribe from) the stream
      var cts = new CancellationTokenSource();

      // Run the demo in parallel
      Console.WriteLine("Subscribing to two channels in one call and listen to all Notifications coming from them");
      var streamTask = NotificationStreamDemo.Run(cts.Token);

      Console.WriteLine("Waiting for you to press any key");
      Console.ReadKey();

      Console.WriteLine("Cancelling the stream");

      cts.Cancel();
      await Task.WhenAll(streamTask);

      Console.WriteLine("Unsubsribed. Bye Bye");
    }
    catch (Exception ex) {
      Console.WriteLine(ex.ToString());
    }
  }
```

In **NotificationStreamDemo.cs**

```cs
  public static async Task Run(CancellationToken cancellationToken)
  {
    var client = new DeribitClient(EndpointType.Testnet);
    await client.Connect();

    var stream = await client.CreateNotificationStream(
                   new[]
                   {
                     "chart.trades.BTC-PERPETUAL.1",
                     "book.BTC-PERPETUAL.1.1.100ms"
                   });

    await foreach (var item in stream.WithCancellation(cancellationToken)) {
      Console.Write(item.Channel);
      Console.Write(": ");

      if (item.Channel.StartsWith("book.")) {
        var data = item.Data.ToObject<BookGroupNotification>();
        Console.Write(data?.DateTime);
        Console.WriteLine();
      }

      if (item.Channel.StartsWith("chart.")) {
        var data = item.Data.ToObject<ChartTradesNotification>();
        Console.Write(data?.TickDateTime);
        Console.Write(" ");
        Console.Write(data?.Volume);
        Console.WriteLine();
      }
    }

    await client.Disconnect();
  }
```

**Comment by Tradyn** [comment]
Hey, great work!

Not had a change to look / test as yet.
Will do next week.
Thanks for doing this.

**Comment by Tradyn** [comment]
`    private async Task SubscribeTicker(string instrument)
    {
        var subList = new[]
        {
            new TickerSubscriptionParams {InstrumentName = "ETH_2SEP22-2400-C", Interval = "100ms"},
            new TickerSubscriptionParams {InstrumentName = "ETH_2SEP22-2400-P", Interval = "100ms"},
            new TickerSubscriptionParams {InstrumentName = "ETH_2SEP22-2200-C", Interval = "100ms"},
        };

        var subscriptions = await _client.SubscribeTicker(subList, async notifications =>
        {
            foreach (var notification in notifications)
            {
                Log.Debug(
                    $"{notification.InstrumentName} ask:{notification.BestAskPrice} bid:{notification.BestBidPrice}");
                _tickers.AddOrUpdate(notification.InstrumentName, notification, (key, value) => notification);
            }
        });
    }`

**Comment by psollberger** [comment]
If I understand correctly, you only want to be able to subscribe to multiple channels of the same type?

**Comment by Tradyn** [comment]
https://github.com/psollberger/DeriSock/blob/35-add-array-of-channels-for-subscriptio/src/DeriSock/SubscriptionManager.cs

`public async Task<SubscriptionToken> Subscribe(ISubscriptionChannel channel, Action<Notification>? callback)`

This should take an array of channels.

`var subscribeResponse = await _client.Send(
                                IsPrivateChannel(channelName) ? "private/subscribe" : "public/subscribe",
                                new
                                {
                                  channels = new[]
                                  {
                                    channelName
                                  }
                                },
                                new ListJsonConverter<string>()).ConfigureAwait(false);`

Line 179: 
The _client.Send sends array of channels, but there is only a single channel added from this method.
So every request sends a single channel subscription, but it should have array of channels.

`public async Task<SubscriptionToken> Subscribe(ISubscriptionChannel[] channels, Action<Notification[]>? callbacks)`

I don't really understand the callbacks code, this is the part that COULD be replaced with RX AFAIK, doesn't NEED to be obviously.
So I am not sure how to implement the array notifications.


_So you have a single method call to send request for multiple channels of same type (ticker, books etc)_
This stops us using requests.


Hope this makes sense?



<img width="475" alt="image" src="https://user-images.githubusercontent.com/17220028/185756158-fa085f72-a9f4-4f77-a1f3-96efe1dd37f4.png">


Image from test api, you add array of channels to the send request for that channel

**Comment by psollberger** [comment]
Thank you for your explanations. I think I have a good idea how to implement that now.
