### ISSUE TITLE
Example required for new refactoring with interfaces

### ISSUE THREAD

**Issue by Tradyn** [psollberger/DeriSock#37]
Hi,

I noticed there is not an example for the new changes.

Please could you add a simple example?

apologies for opening multiple issues

**Comment by psollberger** [comment]
No worries, you are always welcome to create any issue you see necessary.

I realized I made mistakes in generating the classes from the documentation. So I'm working on that with first priority to finally get that straight.

Furthermore the documentation just has changed. Deribit introduced new properties into existing objects and also added new methods as well. For examle, there is a new method category "Combo Books".

I'll make sure to add documentation as soon as possible. At least I'll update the README to reflect the changes there at least.

**Comment by Tradyn** [comment]
I was going to add the combos today.
Very important.
Most important update will be the array of subscriptions.
I have to throttle individual requests currently to sub to tickers, when it could be done in one request.
I have started an interface for this too, unified to make connecting easier.
