### ISSUE TITLE
PublicGetInstruments does not return array of instruments

### ISSUE THREAD

**Issue by Tradyn** [psollberger/DeriSock#38]
var instruments = await _client.PublicGetInstruments(new PublicGetInstrumentsRequest{Currency = currency, Expired = false});

Looks to derserialize single object not array.
Its generated code so I have no idea how to fix this..?

**Comment by psollberger** [comment]
Hi @Tradyn 

I just pushed newly generated code. Hopefully the last time.

The library is now organized in scopes and categories (except subscriptions for obvious reasons).

Your call will now be:
`var instr = await _client.Public.GetInstruments(new PublicGetInstrumentsRequest { Currency = CurrencySymbol.BTC });`
-- or --
`var instr = await _client.MarketData.PublicGetInstruments(new PublicGetInstrumentsRequest { Currency = CurrencySymbol.BTC });`

Both is the same thing. You can use what you prefer.

Please try this and tell me your results.

**Comment by Tradyn** [comment]
Thankyou
