### ISSUE TITLE
Expose async stream as an array when array is sent

### ISSUE THREAD

**Issue by Tradyn** [psollberger/DeriSock#46]
**Is your feature request related to a problem? Please describe.**
On some streams like UserOrders / Trades an array is sent.. This is then enumerated to notify.
But..... We need the array of objects to add to collection / database rather than individual trades/orders

**Describe the solution you'd like**

    public async Task SubscribeUserOrdersByInstrument(string[] instruments, CancellationToken cts)
    {
        var subscribeList = new List<UserOrdersInstrumentChangeChannel>();
        foreach (var instrument in instruments)
        {
            var sub = new UserOrdersInstrumentChangeChannel
                {InstrumentName = instrument, Interval = NotificationInterval1._100ms};
            subscribeList.Add(sub);
        }

        var subscriptionStream =
            await _client.Subscriptions.SubscribeUserOrdersInstrumentChange(subscribeList.ToArray());
        await foreach (var stream in subscriptionStream.WithCancellation(Cts.Token))
        {
            var notification = stream.Data;
            Log.Debug($"[user order] {notification?.InstrumentName}");
            _userOrders.AddOrUpdate(notification?.InstrumentName, notification, (key, value) => notification);
        }

       // Below is from a NugetPackage but it then messes the cancellation token for the other methods..
       // Not sure how to access the array
        //await HandleOrders(subscriptionStream.ToListAsync(Cts.Token));
    }

**Describe alternatives you've considered**
ToListAsync method to expose the whole array 

**Additional context**

**Comment by Tradyn** [comment]
NotificationStream.cs

So this needs a method to convert stream to a list or array I think...

**Comment by psollberger** [comment]
Maybe I don't understand this well enough, but currently this makes no sense to me.

I don't get an array from the API, I get single Notifications and those notifications are passed 1 to 1 into the notification stream.
In addition, a notification stream is continuous, meaning the `ToListAsync` would never complete, because there isn't any end it could possibly reach. It essentially would be a second stream.

**Comment by Tradyn** [comment]
The old version of library had this

<img width="608" alt="image" src="https://user-images.githubusercontent.com/17220028/186725467-cbf64c47-0517-4ec7-b689-107bf0a727fb.png">

json from docs sends array

{
  "params" : {
    "data" : [
      {
        "time_in_force" : "good_til_cancelled",
        "replaced" : false,
        "reduce_only" : false,
        "profit_loss" : 0,
        "price" : 10460.43,
        "post_only" : false,
        "original_order_type" : "market",
        "order_type" : "limit",
        "order_state" : "open",
        "order_id" : "4",
        "max_show" : 200,
        "last_update_timestamp" : 1581507159533,
        "label" : "",
        "is_liquidation" : false,
        "instrument_name" : "BTC-PERPETUAL",
        "filled_amount" : 0,
        "direction" : "buy",
        "creation_timestamp" : 1581507159533,
        "commission" : 0,
        "average_price" : 0,
        "api" : false,
        "amount" : 200
      }
    ],
    "channel" : "user.orders.BTC-PERPETUAL.100ms"
  },
  "method" : "subscription",
  "jsonrpc" : "2.0"
}




*******************************************************
TICKER only sends single ticker object which is correct

<img width="817" alt="image" src="https://user-images.githubusercontent.com/17220028/186725966-0a8f056c-fdc1-4f67-8d7f-fbd6284a480e.png">



{
  "params" : {
    "data" : {
      "timestamp" : 1623060194301,
      "stats" : {
        "volume_usd" : 284061480,
        "volume" : 7871.02139035,
        "price_change" : 0.7229,
        "low" : 35213.5,
        "high" : 36824.5
      },
      "state" : "open",
      "settlement_price" : 36169.49,
      "open_interest" : 502097590,
      "min_price" : 35898.37,
      "max_price" : 36991.72,
      "mark_price" : 36446.51,
      "last_price" : 36457.5,
      "interest_value" : 1.7362511643080387,
      "instrument_name" : "BTC-PERPETUAL",
      "index_price" : 36441.64,
      "funding_8h" : 0.0000211,
      "estimated_delivery_price" : 36441.64,
      "current_funding" : 0,
      "best_bid_price" : 36442.5,
      "best_bid_amount" : 5000,
      "best_ask_price" : 36443,
      "best_ask_amount" : 100
    },
    "channel" : "ticker.BTC-PERPETUAL.raw"
  },
  "method" : "subscription",
  "jsonrpc" : "2.0"
}

**Comment by Tradyn** [comment]
So when an array is sent via websocket it gets enumerated and sent to Notification stream.. but the array from the stream needs to be accessed and not enumerated sometimes.

Sending an array via single commands to DB when it can be done in 1 call is very important.

This was all working in previous version
