### ISSUE TITLE
GetPortfolioMargins returns JObject instead of class PortfolioMarginsResponse

### ISSUE THREAD

**Issue by Tradyn** [psollberger/DeriSock#57]
**Describe the bug**
GetPortfolioMargins returns JObject instead of class

**To Reproduce**

**Expected behavior**

      [JsonProperty("vol_range", NullValueHandling = NullValueHandling.Ignore)]
      public decimal[] VolRange { get; set; }
    
      [JsonProperty("vega_pow2", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? VegaPow2 { get; set; }
    
      [JsonProperty("vega_pow1", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? VegaPow1 { get; set; }
    
      [JsonProperty("skew", NullValueHandling = NullValueHandling.Ignore)]
      public long? Skew { get; set; }
    
      [JsonProperty("price_range", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? PriceRange { get; set; }
    
      [JsonProperty("opt_sum_continguency", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? OptSumContinguency { get; set; }
    
      [JsonProperty("opt_continguency", NullValueHandling = NullValueHandling.Ignore)]
      public long? OptContinguency { get; set; }
    
      [JsonProperty("kurtosis", NullValueHandling = NullValueHandling.Ignore)]
      public long? Kurtosis { get; set; }
    
      [JsonProperty("int_rate", NullValueHandling = NullValueHandling.Ignore)]
      public long? IntRate { get; set; }
    
      [JsonProperty("initial_margin_factor", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? InitialMarginFactor { get; set; }
    
      [JsonProperty("ftu_continguency", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? FtuContinguency { get; set; }
    
      [JsonProperty("atm_range", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? AtmRange { get; set; }
    
      [JsonProperty("projected_margin_pos", NullValueHandling = NullValueHandling.Ignore)]
      public long? ProjectedMarginPos { get; set; }
    
      [JsonProperty("projected_margin", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? ProjectedMargin { get; set; }
    
      [JsonProperty("position_sizes", NullValueHandling = NullValueHandling.Ignore)]
      public Dictionary<string, long> PositionSizes { get; set; }
    
      [JsonProperty("pls", NullValueHandling = NullValueHandling.Ignore)]
      public decimal[] Pls { get; set; }
    
      [JsonProperty("pco_opt", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? PcoOpt { get; set; }
    
      [JsonProperty("pco_ftu", NullValueHandling = NullValueHandling.Ignore)]
      public long? PcoFtu { get; set; }
    
      [JsonProperty("opt_summary", NullValueHandling = NullValueHandling.Ignore)]
      public OptSummary[] OptSummary { get; set; }
    
      [JsonProperty("opt_pls", NullValueHandling = NullValueHandling.Ignore)]
      public decimal[] OptPls { get; set; }
    
      [JsonProperty("opt_entries", NullValueHandling = NullValueHandling.Ignore)]
      public OptEntry[] OptEntries { get; set; }
    
      [JsonProperty("margin_pos", NullValueHandling = NullValueHandling.Ignore)]
      public long? MarginPos { get; set; }
    
      [JsonProperty("margin", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? Margin { get; set; }
    
      [JsonProperty("ftu_summary", NullValueHandling = NullValueHandling.Ignore)]
      public object[] FtuSummary { get; set; }
    
      [JsonProperty("ftu_pls", NullValueHandling = NullValueHandling.Ignore)]
      public long[] FtuPls { get; set; }
    
      [JsonProperty("ftu_entries", NullValueHandling = NullValueHandling.Ignore)]
      public object[] FtuEntries { get; set; }
    
      [JsonProperty("co_opt", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? CoOpt { get; set; }
    
      [JsonProperty("co_ftu", NullValueHandling = NullValueHandling.Ignore)]
      public long? CoFtu { get; set; }
    
      [JsonProperty("calculation_timestamp", NullValueHandling = NullValueHandling.Ignore)]
      public long? CalculationTimestamp { get; set; }
    }
    
    public partial class OptEntry
    {
      [JsonProperty("underlying_price", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? UnderlyingPrice { get; set; }
    
      [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
      public long? Size { get; set; }
    
      [JsonProperty("iv_pl_vec3", NullValueHandling = NullValueHandling.Ignore)]
      public decimal[][] IvPlVec3 { get; set; }
    
      [JsonProperty("instrument_name", NullValueHandling = NullValueHandling.Ignore)]
      public string InstrumentName { get; set; }
    
      [JsonProperty("exp_tstamp", NullValueHandling = NullValueHandling.Ignore)]
      public long? ExpTstamp { get; set; }
    }
    
    public partial class OptSummary
    {
      [JsonProperty("iv_pl_vec3", NullValueHandling = NullValueHandling.Ignore)]
      public decimal[][] IvPlVec3 { get; set; }
    
      [JsonProperty("exp_tstamp", NullValueHandling = NullValueHandling.Ignore)]
      public long? ExpTstamp { get; set; }
    
      [JsonProperty("abs_qty", NullValueHandling = NullValueHandling.Ignore)]
      public decimal? AbsQty { get; set; }
    }

**Additional context**

**Comment by Tradyn** [comment]
Awesome work thank so much for doing all this

**Comment by Tradyn** [comment]
Deribit have added some history endpoints.. would be good to have those added with a way to download in batches.

**Comment by psollberger** [comment]
The API docs haven't changed. I'm intrigued, what endpoints are you talking about?

**Comment by Tradyn** [comment]
https://twitter.com/deribitexchange/status/1570135181033607168?s=46&t=cO43TNgJbB3xIfc92KTAHA
