### ISSUE TITLE
Two bugs in subscriptions to private streams

### ISSUE THREAD

**Issue by AndreyVasilchenko** [psollberger/DeriSock#60]
Hi! In user event subscriptions, I found two bugs due to which events did not arrive in the event stream queue. Please make the following corrections:
![Bug(Positions)](https://user-images.githubusercontent.com/32433994/190222853-aa6943e6-350f-4357-8295-670bdc3b6f71.png)
![Bug(PortfolioName)](https://user-images.githubusercontent.com/32433994/190222891-116cedcb-7065-4b94-8e2e-ca3fd94e58bd.png)

**Comment by psollberger** [comment]
Hi @AndreyVasilchenko 

The first image shows a bug in the API documentation. There are many of those mistakes. I fixed that.

For the second image: Why?
The API Console sends the currency as-is. So i see no reason to change that.

![image](https://user-images.githubusercontent.com/10230562/190476196-fabfee0a-2da5-4432-aa4a-3832218bd81c.png)

**Comment by AndreyVasilchenko** [comment]
Unfortunately, you are wrong - look at the event context from the server:

![Bug(PortfolioName)2](https://user-images.githubusercontent.com/32433994/190486753-e3643968-0103-44ad-8c3a-3f15ca27ce3c.png)

If you do not change the code, as I showed, then you will end up not receiving event messages at all ...
