### ISSUE TITLE
I propose to make an addition to the event subscription code.

### ISSUE THREAD

**Issue by AndreyVasilchenko** [psollberger/DeriSock#61]
To avoid constantly iterating the last element in the subscription event receiving loop and getting it only once when the event message is received, I suggest making the following small addition:
![Bug(EditEnummerator)](https://user-images.githubusercontent.com/32433994/190233797-8c7ccedb-8016-4871-9e34-b975eae723e3.png)

**Comment by AndreyVasilchenko** [comment]
But it seems to me that it is better to implement this function like this:

`
  /// <inheritdoc />
  async ValueTask<bool> IAsyncEnumerator<Notification<T>>.MoveNextAsync()
  {
    try {

      _current = null;

      while (!_cancellationToken.IsCancellationRequested) 
      {
        if (((INotificationStream)this).Queue.TryDequeue(out var next))
        {
          if (next is not null)
          {
            _current = next.ConvertTo<T>();
            return true;
          }
        }
        await Task.Delay(1, _cancellationToken).ConfigureAwait(false);
      }

      return false;
    }
    catch (TaskCanceledException) {
      return false;
    }
  }

`

**Comment by AndreyVasilchenko** [comment]
I'm sorry, apparently I pressed something wrong on the keyboard and the issues was closed )

**Comment by psollberger** [comment]
Can you please elaborate on what exactly this will improve?

**Comment by AndreyVasilchenko** [comment]
![Bug(EditEnummerator)2](https://user-images.githubusercontent.com/32433994/190495445-f7ffdfcc-e4d8-476d-ab9e-2de1e7668bc3.png)

This loop does not work correctly: when an event arrives, there are countless iterations with this event until a new event arrives and many iterations begin with it too. With the code options I suggested, the loop makes exactly one iteration with the newly arrived event.

**Comment by psollberger** [comment]
Now I got it. Thank you!

**Comment by AndreyVasilchenko** [comment]
Many thanks to you, too, for your attention and efficiency!
