### ISSUE TITLE
Unfortunately, you are wrong - look at the event context from the server:

### ISSUE THREAD

**Issue by AndreyVasilchenko** [psollberger/DeriSock#62]
Unfortunately, you are wrong - look at the event context from the server:

![Bug(PortfolioName)2](https://user-images.githubusercontent.com/32433994/190486753-e3643968-0103-44ad-8c3a-3f15ca27ce3c.png)

If you do not change the code, as I showed, then you will end up not receiving event messages at all, as it is now happening...

_Originally posted by @AndreyVasilchenko in https://github.com/psollberger/DeriSock/issues/60#issuecomment-1248485292_

**Comment by psollberger** [comment]
I see what you mean. I fixed it more globally now.
