### ISSUE TITLE
Problem when there is a loss (break) of communication with the API server socket

### ISSUE THREAD

**Issue by AndreyVasilchenko** [psollberger/DeriSock#65]
Good afternoon!
There is a serious problem when there is a loss (break) of communication with the API server socket (especially when the connection is disconnected for a long time) in the handler for receiving messages by subscriptions and the handler for sending messages (class: DefaultJsonRpcMessageSource  methods: Send() and GetMessageStream()). When the connection is broken, work is obtained in endless loops, which greatly increases the load on the computer processor, while the software application using the SDK does not receive information about the connection break through the "Disconnected" event ...

At the moment I'm solving this problem in this way:

![Bug GetMessageStream](https://user-images.githubusercontent.com/32433994/194003128-f3cd02a3-aa7e-48d2-90f4-8c617c14b6a6.png)

This allows you to break out of the infinite loop, and send a message to the user application about the "Disconnected" event.

**Comment by psollberger** [comment]
Thank you very much for bringing this to my attention. I will investigate it as soon as I have sufficient time for it.
