### ISSUE TITLE
Issue reconnecting to API server socket when using DefaultJsonRpcMessageSource.Reconnect() method

### ISSUE THREAD

**Issue by AndreyVasilchenko** [psollberger/DeriSock#66]
Now, when the DefaultJsonRpcMessageSource.Reconnect() method is executed, a connection is made to a new API server socket, and as a result of this change, all subscriptions (public and user) to events made in the user application and using this SDK are lost.

When executing this method:

1. There is no restoration of subscriptions to data streams that were made when using the previous socket. 
       
     We kindly request:
 Add the restoration of subscriptions that were created when connecting via the previous socket. If this is not done, then the whole point of using subscriptions disappears, since streams are periodically interrupted, and this, accordingly, leads to an uncontrolled stop of the correct operation of the user application.

2. The user application does not receive messages about the loss and subsequent change of connection to the API server. 
      
      Request: 
Add the ability to subscribe to the "Reconnect" event to the DeribitClient class so that the user application has the ability to timely monitor the health of subscriptions to streaming events.

**Comment by AndreyVasilchenko** [comment]
Unfortunately, I cannot agree with you - my practice has shown me the opposite, and therefore I specifically contacted the developers of the Deribit API. The developers gave me a one-shot answer: subscriptions to notification streams exist only as long as the web socket is active. Since a connection is made to a different socket and a new authentication is performed, all subscriptions must be made again. It is because of this that I have singled out this case as a separate problem.

Thank you for your prompt response and understanding.

**Comment by psollberger** [comment]
That's true. The subscriptions are gone when the socket is closed.

But I talked about the NotificationStream objects implemented inside DeriSock.
They are not bound to the network socket and thus still exist and would be able to receive further notifications.
They just don't receive any notifications because the client doesn't re-subscribe to the channels the NotificationStreams want to listen to.

**Comment by AndreyVasilchenko** [comment]
It is for this that I wrote request item No.2 in the description of this problem, if you do not have the opportunity to implement request item No.1. But for developers using your SDK, it will be better if you do both points )
