### ISSUE TITLE
PrivateGetUserTradesByCurrencyAndTime trying to deserialize into wrong type

### ISSUE THREAD

**Issue by gabfeldman** [psollberger/DeriSock#7]
https://github.com/psollberger/DeriSock/blob/47b508ee02fb4c8fd16aa5c36b69236b3b271a56/DeriSock/DeribitV2Client.cs#L1967

Here it should be UserTradeCollection instead of UserTrade[]

I tried creating a branch, but I don't think I have permission. Would you be able to fix this?
By the way, it would be great if you could put a package in Nuget.
Thanks

**Comment by psollberger** [comment]
Fixed with PR #8
