### ISSUE TITLE
Request for WebProxy support

### ISSUE THREAD

**Issue by badokun** [psollberger/DeriSock#70]
https://github.com/psollberger/DeriSock/blob/aa514b8229c741447825446e5f324db3f7808e5c/src/DeriSock/Net/TextMessageWebSocketClient.cs#L48

I'd like to add support for using a socks5 proxy. While I can implement an `ITextMessageClient` to support that, the existing sealed class, `TextMessageWebSocketClient` looks good as it is.

Below is an example of how it can be used:

```
  /// <inheritdoc />
  public async Task Connect(Uri endpoint, CancellationToken cancellationToken = default)
  {
    if (IsConnected)
      throw new InvalidOperationException();

    _webSocketEndpoint = endpoint;

    _webSocket = new ClientWebSocket()
    {
      Options =
      {
        Proxy = new WebProxy(new Uri("socks5://socks5.xxxx.net:1080"))
        {
          Credentials = new NetworkCredential()
          {
            UserName = "",
            Password = ""
          }
        }
      }
    };
....
```

By modifying the Connect method taking in an optional ClientWebSocket object, we can support this request. What do you think?

```
   /// <inheritdoc />
  public async Task Connect(Uri endpoint, CancellationToken cancellationToken = default, ClientWebSocket? clientWebSocket = default)
  {
    if (IsConnected)
      throw new InvalidOperationException();

    _webSocketEndpoint = endpoint;

    _webSocket = clientWebSocket ?? new ClientWebSocket();
    _logger?.Information("Connecting to {Endpoint}", _webSocketEndpoint);

```
The method signature on the interface would also need to be updated to take the optional parameter. 

In the example above I placed the parameter at the end so it doesn't break elsewhere in the solution but if given the choice I think the cancellationToken should always be the last one.

**Comment by badokun** [comment]
On closer inspection maybe a custom ITextMessageClient implementation is better. Can that class be unsealed?

**Comment by psollberger** [comment]
Thank you very much for your suggestion. I take a look into it.

**Comment by psollberger** [comment]
I updated the readme with usage instructions:

```cs
// Use a web proxy to connect to the API

var messageSource = new TextMessageWebSocketClient(null);
messageSource.Proxy = new WebProxy("socks5://socks5.example.com:1080")
{
  Credentials = new NetworkCredential
  {
    UserName = "username",
    Password = "password"
  }
};

var clientWithProxy = new DeribitClient(EndpointType.Testnet, messageSource);
```

**Comment by badokun** [comment]
Thank you so much
